[package]
name = "pomo"
version = "0.1.2"
authors = ["Kevin Peek <kevpeek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
indicatif = "0.14.0"
dialoguer = "0.5.0"
rodio = "0.10.0"
