[package]
name = "pomo"
version = "0.1.0"
authors = ["Kevin Peek <kevpeek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "3"
clap = "2.33.0"