name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
    - name: Setup
      run: sudo apt-get install --assume-yes libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
